- name: upload nginx.conf
  bacame: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    owner: www-data
    group: www-data
    mode: '0400'
