- name: Add php repository
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ondrej/php

- name: Install php packages
  become: true
  apt:
    pkg:
      - php-cli
      - php-fpm
      - php-xml
      - php-imap
      - php-intl
      - php-mbstring
      - php-bz2
      - php-zip
      - php-curl
      - php-gd
      - php-imagick
      - php-mysql
      - php-pgsql
      - php-sqlite3
      - php-redis
      - php-bcmath

# https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos
- name: Download composer
  get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: "{{ ansible_env.HOME }}/.local/bin/composer"
    mode: 0755
